language: c

before_install:
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

# Add I2P and Mono repositories
 - travis_retry sudo apt-add-repository -y ppa:i2p-maintainers/i2p
 - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
 - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list

# Updates ubuntu repo
 - travis_retry sudo apt-get update

###############
# Install I2P #
##############
 - travis_retry sudo apt-get install i2p
 - sudo sed -i /etc/default/i2p -e 's/RUN_DAEMON="false"/RUN_DAEMON="true"/'

# This generates the initial configuration
 - sudo service i2p start
 - sudo service i2p stop

# Open up the SAM and BOB bridges
 - sudo sed -i /var/lib/i2p/i2p-config/clients.config -e 's/clientApp.1.startOnLoad=false/clientApp.1.startOnLoad=true/'
 - sudo sed -i /var/lib/i2p/i2p-config/clients.config -e 's/clientApp.5.startOnLoad=false/clientApp.5.startOnLoad=true/'

 - sudo cat /var/lib/i2p/i2p-config/clients.config
 - sudo service i2p start


################
# Install mono #
################
 - sudo apt-get install mono-devel fsharp nuget

# Wait until SAM and BOB bridges are open
 - nc -zvv localhost 7656; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 7656..."; nc -zvv localhost 7656; out=$?; sleep 1; done
 - nc -zvv localhost 2827; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 2827..."; nc -zvv localhost 2827; out=$?; sleep 1; done

install:
 - travis_retry nuget restore
 - travis_retry nuget install NUnit.Runners

script:
 - xbuild
 - mono NUnit.Runners.2.6.4/tools/nunit-console.exe -labels Futsi.Tests/bin/Debug/Futsi.Tests.dll
